### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by jkopano** [chebro/calendar-notification#4]
Hello!
so after last time, today (with pretty much larger knowledge at scripting i think)
i wanted to try your script again and found out what didn't work for me last time, basically the $1 as input for cal command was invalid, its outputting 
"year `' not in range 1..9999"
so i just removed it and calendar at least show itself, but not exactly how i _wanted it to_ 
https://imgur.com/a/CWAUXry
Can you give me so tips ? Should i change dunst config or just try my hand with sed?
Thank you very much
 
Edit: just saw your reply to my last post and now i feel stupid 

Edit2: ok so i changed dunst config a little bit and have something like this:
https://imgur.com/a/CqnrbIR
it seems that highlighting is making this spacing in the center of calendar, i will try to remove it.

EDIT3:
So after some odd things i found this (ncal -b -h ) to be working perfectly, i hope this will help someone out.

**Comment by chebro** [comment]
> So after some odd things i found this (ncal -b -h ) to be working perfectly, i hope this will help someone out.

glad you could find a fix, i'll leave this issue open for posterity!
